version: 2.1
orbs:
  python: circleci/python@2.0.3
  slack: circleci/slack@3.4.2
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest




workflows:
  sample:
    jobs:
      - build-and-test
      - hold:
          type: approval
          requires:
            - build-and-test
      - slack/approval-notification:
          requires:
            - build-and-test
          message: testing-flask Pending approval to deploy

