version: 2.1
orbs:
  python: circleci/python@2.0.3
  slack: circleci/slack@3.4.2
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f7:d2:6a:2b:e3:88:73:96:85:a8:8c:31:da:59:03:cd"
      - run:
          name: Deploy Over SSH
          command: |
            ssh ubuntu@sgh-jarvis-empower.com "cd test/testing-flask-with-pytest"
            ssh ubuntu@sgh-jarvis-empower.com "sudo FLASK_APP=api.py flask run"
      - slack/notify:
          color: '#42e2f4'
          message: testing-flask deploy to server completed.


workflows:
  sample:
    jobs:
      - build-and-test
      - hold:
          type: approval
          requires:
            - build-and-test
      - slack/approval-notification:
          requires:
            - build-and-test
          message: EMPOWER-flask Pending approval to deploy
      - deploy:
          requires:
            - hold


