version: 2.1
orbs:
  python: circleci/python@2.0.3
  slack: circleci/slack@4.9.3
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - slack/notify:
          event: pass
          template: basic_success_1
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  sample:
    jobs:
      - build-and-test
      - slack/on-hold:
          requires:
            - build-and-test
      - pause_workflow:
          requires:
            - build-and-test
            - slack/on-hold
          type: approval


